version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: stock-control-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: stock-control-db
      POSTGRES_USER: nap_creativa
      POSTGRES_PASSWORD: NapcreativaDb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nap_creativa -d stock-control-db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
